stages:
  - deploy

deploy_production:
  stage: deploy
  only:
    - main
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts
    - ssh -p 52173 "$DEPLOY_USER@$DEPLOY_HOST" "cd $DEPLOY_PATH && git pull && docker compose up -d --build"
